# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/lt02ltespr/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/lt02ltespr/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/samsung/lt02ltespr/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/samsung/lt02ltespr/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/samsung/lt02ltespr/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/samsung/lt02ltespr/proprietary/bin/e2fsck:system/bin/e2fsck \
    vendor/samsung/lt02ltespr/proprietary/bin/geomagneticd:system/bin/geomagneticd \
    vendor/samsung/lt02ltespr/proprietary/bin/gzip:system/bin/gzip \
    vendor/samsung/lt02ltespr/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/samsung/lt02ltespr/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/lt02ltespr/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/samsung/lt02ltespr/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/samsung/lt02ltespr/proprietary/bin/orientationd:system/bin/orientationd \
    vendor/samsung/lt02ltespr/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/samsung/lt02ltespr/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/lt02ltespr/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/samsung/lt02ltespr/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/lt02ltespr/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/lt02ltespr/proprietary/bin/thermal-engine:system/bin/thermal-engine \
    vendor/samsung/lt02ltespr/proprietary/bin/thermald:system/bin/thermald \
    vendor/samsung/lt02ltespr/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/samsung/lt02ltespr/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/lt02ltespr/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/lt02ltespr/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/samsung/lt02ltespr/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/samsung/lt02ltespr/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/samsung/lt02ltespr/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/samsung/lt02ltespr/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/samsung/lt02ltespr/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/samsung/lt02ltespr/proprietary/etc/firmware/wlan/prima/WCNSS_cfg.dat:system/etc/firmware/wlan/prima/WCNSS_cfg.dat \
    vendor/samsung/lt02ltespr/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini:system/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini \
    vendor/samsung/lt02ltespr/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv_noFEM.bin:system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv_noFEM.bin \
    vendor/samsung/lt02ltespr/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin \
    vendor/samsung/lt02ltespr/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/lt02ltespr/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libadsprpc.so:system/lib/libadsprpc.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libaudioparsers.so:system/lib/libaudioparsers.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libCB.so:system/lib/libCB.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libchromatix_imx175_default_video.so:system/lib/libchromatix_imx175_default_video.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libchromatix_imx175_lls.so:system/lib/libchromatix_imx175_lls.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libchromatix_imx175_preview.so:system/lib/libchromatix_imx175_preview.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libchromatix_imx175_zsl.so:system/lib/libchromatix_imx175_zsl.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libchromatix_s5k3h5xa_default_video.so:system/lib/libchromatix_s5k3h5xa_default_video.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libchromatix_s5k3h5xa_lls.so:system/lib/libchromatix_s5k3h5xa_lls.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libchromatix_s5k3h5xa_preview.so:system/lib/libchromatix_s5k3h5xa_preview.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libchromatix_s5k3h5xa_zsl.so:system/lib/libchromatix_s5k3h5xa_zsl.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libchromatix_s5k6a3yx_default_video.so:system/lib/libchromatix_s5k6a3yx_default_video.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libchromatix_s5k6a3yx_preview.so:system/lib/libchromatix_s5k6a3yx_preview.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libchromatix_s5k6a3yx_smart_stay.so:system/lib/libchromatix_s5k6a3yx_smart_stay.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libchromatix_s5k6a3yx_vt_hd.so:system/lib/libchromatix_s5k6a3yx_vt_hd.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libchromatix_s5k6a3yx_vt.so:system/lib/libchromatix_s5k6a3yx_vt.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libcordon.so:system/lib/libcordon.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libExtendedExtractor.so:system/lib/libExtendedExtractor.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libgeofence.so:system/lib/libgeofence.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libhdcp2.so:system/lib/libhdcp2.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmercury.so:system/lib/libmercury.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmmcamera_plugin.so:system/lib/libmmcamera_plugin.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmmmpod.so:system/lib/libmmmpod.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/samsung/lt02ltespr/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so \
    vendor/samsung/lt02ltespr/proprietary/lib/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/lt02ltespr/proprietary/vendor/lib/hw/power.qcom.so:system/vendor/lib/hw/power.qcom.so \
    vendor/samsung/lt02ltespr/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/lt02ltespr/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/lt02ltespr/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/lt02ltespr/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/lt02ltespr/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/lt02ltespr/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/lt02ltespr/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/lt02ltespr/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/lt02ltespr/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so
